version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /srv/cloud/files:/srv
      - /srv/cloud/filebrowser.db:/database.db
    environment:
      PUID: 1000
      PGID: 1000
      FB_AUTH_METHOD: json

